---
- name: Step 001 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  # Executing the playbook directly
  vars_files:
    - "/home/osboxes/Documents/ansible_agnostic_deployer-development/ansible/configs/{{ env_type }}/env_oci_vars.yml"
    - "{{ANSIBLE_REPO_PATH}}/configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - step001
    - deploy_infrastructure

  tasks:
    - import_tasks: oci_ssh_config_setup.yml
    - name: Launch instances
      oci_instance:
        force_create: yes
        availability_domain: "{{ item.instance_ad }}"
        compartment_id: "{{ instance_compartment }}"
        name: "{{ item.name }}"
        image_id: "{{ item.instance_image }}"
        vnic:
            assign_public_ip: True
            #hostname_label: "{{ item.hostname }}"
            subnet_id: "{{ instance_subnet_id }}"
        metadata:
            ssh_authorized_keys: "{{ lookup('file',  my_test_public_key ) }}"
        shape: "{{ item.flavor.oci }}"
        defined_tags:
          TagNamespace1: "{{ item.tag_namespace }}"
        exact_count: "{{ item.exact_count }}"
        count_tag:
          TagNamespace1: "{{ item.tag_namespace }}"
      with_items: 
        - "{{ instances[0] }}"
        - "{{ instances[1] }}"
        - "{{ instances[2] }}"
        - "{{ instances[3] }}"
        - "{{ instances[4] }}"
      register: result